"""Initial migration with SQLite

Revision ID: b6219a9db7ff
Revises: 
Create Date: 2025-08-26 13:30:12.317074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b6219a9db7ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('topic_number', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('completed_topics', sa.JSON(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('learning_style', sa.String(length=20), nullable=True),
    sa.Column('preferred_difficulty', sa.String(length=10), nullable=True),
    sa.Column('learning_pace', sa.String(length=10), nullable=True),
    sa.Column('attention_span_minutes', sa.Integer(), nullable=True),
    sa.Column('prefers_visual_tools', sa.Boolean(), nullable=True),
    sa.Column('prefers_step_by_step', sa.Boolean(), nullable=True),
    sa.Column('prefers_immediate_feedback', sa.Boolean(), nullable=True),
    sa.Column('prefers_gamification', sa.Boolean(), nullable=True),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('total_problems_solved', sa.Integer(), nullable=True),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=True),
    sa.Column('consecutive_correct_streak', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.String(length=10), nullable=True),
    sa.Column('topic_performance', sa.JSON(), nullable=True),
    sa.Column('learning_patterns', sa.JSON(), nullable=True),
    sa.Column('struggle_areas', sa.JSON(), nullable=True),
    sa.Column('strength_areas', sa.JSON(), nullable=True),
    sa.Column('session_frequency', sa.Float(), nullable=True),
    sa.Column('average_session_duration', sa.Integer(), nullable=True),
    sa.Column('tool_usage_preferences', sa.JSON(), nullable=True),
    sa.Column('current_difficulty_level', sa.Float(), nullable=True),
    sa.Column('learning_velocity', sa.Float(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_profile_id', sa.String(), nullable=False),
    sa.Column('topic_number', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('problems_attempted', sa.Integer(), nullable=True),
    sa.Column('problems_correct', sa.Integer(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('mistakes_made', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('help_requests', sa.Integer(), nullable=True),
    sa.Column('time_on_difficult_problems', sa.Integer(), nullable=True),
    sa.Column('mastery_achieved', sa.Boolean(), nullable=True),
    sa.Column('next_recommended_topic', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_sessions')
    op.drop_table('chat_messages')
    op.drop_table('user_progress')
    op.drop_table('student_profiles')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
